#!/bin/sh
# This script removes the model name symlink in /var/run/usbmount/by-label.
# Copyright (C) 2014 Andy Davison
#
# This file is free software; the copyright holder gives unlimited
# permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
set -e

ls /var/run/usbmount/by-label | while read name; do
    if test "`readlink \"/var/run/usbmount/by-label/$name\" || :`" = "$UM_MOUNTPOINT"; then
		rm -f "/var/run/usbmount/by-label/$name"
    fi
done

exit 0
