#!/bin/sh
# This script unmounts the OpenFrame boot partition if it appears.
# Copyright (C) 2014 Andrew Davison
#
# This file is free software; the copyright holder gives unlimited
# permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
set -e

# Exit if device or mountpoint is empty.
test -z "$UM_DEVICE" && test -z "$UM_MOUNTPOINT" && exit 0

# Get volume label name.
LABEL=`blkid -o udev $UM_DEVICE | grep ID_FS_LABEL= | cut -d'=' -f2`

# Get boot volume name from /etc/fstab.
BOOTVOL=`cat /etc/fstab | grep /boot | awk -F\= {'print $2'} | awk -F\  {'print $1'}`

# If the volume label is the same as the boot partition from fstab, unmount it.
if [ "$BOOTVOL" = "$LABEL" ]; then
	umount "$UM_MOUNTPOINT"
	ls /var/run/usbmount | while read name; do
	    if test "`readlink \"/var/run/usbmount/$name\" || :`" = "$UM_MOUNTPOINT"; then
			rm -f "/var/run/usbmount/$name"
	    fi
	done
	ls /var/run/usbmount/by-label | while read name; do
	    if test "`readlink \"/var/run/usbmount/by-label/$name\" || :`" = "$UM_MOUNTPOINT"; then
			rm -f "/var/run/usbmount/by-label/$name"
	    fi
	done
fi

exit 0
