#!/bin/sh

# of-autologin v1.00 (24rd July 2019)
#  Toggles automatic login on tty1 via getty.

AUTOLOGINUSER="$1"
[ $# -ne 1 ] && AUTOLOGINUSER="root"

if [ -f /etc/systemd/system/getty@tty1.service.d/override.conf ]; then
	echo -n "Enabling tty1 autologin for '$AUTOLOGINUSER' user..."
	rm /etc/systemd/system/getty@tty1.service.d/override.conf
	echo " done."
else
	echo -n "Disabling tty1 autologin..."
	echo -e '[Service]\nExecStart=\nExecStart=-/sbin/agetty -a '$AUTOLOGINUSER' --noclear %I $TERM\n' > /etc/systemd/system/getty@tty1.service.d/override.conf
	echo " done."
fi
