#!/bin/bash

# of-install-build v1.03 (8th August 2019)
#  Installs a build environment onto the OpenFrame.

source /etc/lsb-release

KERNELURL="https://dl.birdslikewires.net/openframe/kernel"

if [ "$USER" != "root" ]; then
  echo "You need to run this with superuser privileges."
  exit 1
fi

KERNMAJVER=`uname -r | awk -F. '{print $1}'`
KERNMIDVER=`uname -r | awk -F. '{print $2}'`
KERNMINVER=`uname -r | awk -F. '{print $3}'`

KERNELFETCHURL="$KERNELURL"/"${DISTRIB_ID,,}"/"${DISTRIB_CODENAME,,}"/"$KERNMAJVER"."$KERNMIDVER"/`uname -r`
echo $KERNELFETCHURL

echo -n "Downloading `uname -r` kernel packages..."
mkdir -p /tmp/`uname -r`
if wget -q -r -l1 -np -nd -P /tmp/`uname -r` -A .deb $KERNELFETCHURL; then

	echo " done."
	echo "Installing headers..."
	dpkg -i /tmp/`uname -r`/linux-headers*.deb
	echo "Installing build-essential..."
	apt-get update
	apt-get -y install build-essential
	echo "Complete!"
	exit 0

else

	echo "Download failed."
	exit 1

fi
