#!/bin/bash

## openframe-identifier v2.11 (24th July 2019)
##  Identifies what kind of OpenFrame device we're running on and applies some tweaks.

OPENFRAME="1"
KERNMAJVER=`uname -r | awk -F. '{print $1}'`

applystac9202pinpatch() {
	if [ ! -f /etc/modprobe.d/of1-stac9202.conf ]; then
		echo -n "Applying STAC9202 audio configuration..."
		echo "options snd-hda-intel position_fix=1 bdl_pos_adj=64 patch=of1-stac9202.patch" > /etc/modprobe.d/of1-stac9202.conf
		/sbin/alsa force-reload &>/dev/null
		echo " done."
	fi
}

removestac9202pinpatch() {
	if [ -f /etc/modprobe.d/of1-stac9202.conf ]; then
		echo -n "Removing STAC9202 audio configuration..."
		rm /etc/modprobe.d/of1-stac9202.conf
		/sbin/alsa force-reload &>/dev/null
		echo " done."
	fi
}

if [ -e /boot/openframe.ver ]; then

	# Look for an override file.
	OPENFRAME=`cat /boot/openframe.ver | cut -b1`
	MMCSIZE=""
	echo "Identified an OpenFrame $OPENFRAME from override file."

else

	MMC=`/bin/ls -1 /dev/mmcblk* 2>/dev/null | grep -v "p"`

	if [ "$MMC" != "" ]; then

		MMCCOUNT=`/bin/echo "$MMC" | /usr/bin/wc -l`

		if [ $MMCCOUNT -le 1 ];  then

			# If only one /dev/mmcblk appears, we can use it to identify the unit.

			MMCNUM=`echo "${MMC: -1}"`
			MMCSIZE=`/sbin/fdisk -l /dev/mmcblk$MMCNUM | grep mmcblk$MMCNUM: | awk -F\  {'print $5'}`

			if [ $MMCSIZE -gt 1028128768 ]; then
				OPENFRAME=2
			fi

			if [ $MMCSIZE -gt 0 ]; then
				echo "OpenFrame $OPENFRAME with "$(($MMCSIZE/1024/1024))" MB internal storage."
			else
				echo "Could not identify MMC capacity. Assuming OpenFrame 1."
			fi

		else

			# If we get more than one, we can't guarantee which is the internal one.
			echo "Multiple MMC devices found. Assuming OpenFrame 1."

		fi

	else

		echo "Could not identify an MMC device. Assuming OpenFrame 1."

	fi

fi

[ ! $OPENFRAME ] || [ $OPENFRAME -lt 1 ] || [ $OPENFRAME -gt 2 ] && echo "Not a known device." && exit 1

echo $OPENFRAME > /tmp/openframe.ver

if [ -f /root/resize ]; then
	echo "Resizing root filesystem."
	/sbin/resize2fs `cat /root/resize`
	rm /root/resize
	/usr/bin/aplay -q -f a_law -r 44100 /usr/local/share/sounds/success.au &
fi

if [ "$OPENFRAME" -eq 1 ]; then

	## Here be the OpenFrame 1 tweaks.

	# If the kernel is from the 3.x series, we'll be using the patch.
	[ $KERNMAJVER -eq 3 ] && applystac9202pinpatch
	# More modern kernels... they're on their own. Good luck!
	[ $KERNMAJVER -gt 3 ] && removestac9202pinpatch

elif [ "$OPENFRAME" -eq 2 ]; then

	## Here be the OpenFrame 2 tweaks.

	# Ensure that the OpenFrame 1's audio firmware patch is removed.
	removestac9202pinpatch

else

	echo "Unable to identify this device. Is it an OpenFrame?"
	exit 1

fi

exit 0
