#!/bin/bash

# of-keycheck v1.02 (1st July 2019)
#  Regenerate the key files if they're not present.

[ ! -f /etc/ssh/ssh_host_rsa_key ] && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server &>/tmp/of-keycheck.log && exit 0
