#!/bin/bash

# of-xorg v1.31 (29th August 2018)
#  Installs Xorg server.

#set -x

if [ "$USER" != "root" ]; then
  echo "You need to run this with superuser privileges."
  exit 1
fi

apt-get update

echo "Installing Xorg..."
echo
apt-get -y install xinit xterm
echo

if [[ "$@" == "mplayer" ]]; then
	echo "Installing mplayer..."
	echo
	apt-get -y install mplayer
	echo -e "\n###OpenFrame Specific\nao=alsa\nva=x11\nzoom=yes\nfs=yes" >> /etc/mplayer/mplayer.conf
	echo -e "\n###OpenFrame Specific\nMOUSE_BTN0_DBL quit\nMOUSE_BTN0-MOUSE_BTN0_DBL quit" >> /etc/mplayer/input.conf
	echo
fi

## Dealt with in of-prep.
# echo "Setting sensible audio level..."
# echo
# /usr/bin/amixer -c 0 sset "Master" 50% unmute
# echo

echo "Setting Xorg permissions..."
chmod ug+s /usr/lib/xorg/Xorg
sed -i 's/allowed_users=console/allowed_users=anybody/g' /etc/X11/Xwrapper.config
echo

echo "Setting XTerm geometry..."
echo "*xterm*geometry: 132x36+0+0" >> /etc/X11/app-defaults/XTerm
echo

echo "Redirecting error file to null..."
sed -i 's/\ERRFILE=$HOME/ERRFILE=\/dev\/null/g' /etc/X11/Xsession

if [ -f /etc/systemd/system/getty@tty1.service.d/override.conf ]; then
	echo "Disabling auto-login on tty1..."
	mv /etc/systemd/system/getty@tty1.service.d/override.conf /etc/systemd/system/getty@tty1.service.d/override.conf.disabled
fi

# echo "Updating initramfs..."
# sleep 2
# echo
# depmod -a
# update-initramfs -u

sync
sync
echo "Xorg setup complete."

exit 0
