#!/bin/sh
#
# logroller v1.02 (27th November 2014)
#
### BEGIN INIT INFO
# Provides:          logroller
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Backs up logs on tmpfs into a .tgz.
# Description:       Backs up logs on tmpfs into a .tgz, just in case.
### END INIT INFO

LOGROLL="/var/logroll.tgz"

[ -f $LOGROLL ] && /bin/rm $LOGROLL

echo -n "Backing up logs to $LOGROLL..."
/bin/tar zcPf $LOGROLL /var/log &>/dev/null
echo " done."
exit 0
