#!/bin/sh
#
# preptmpfs v1.06 (27th November 2014)
#
### BEGIN INIT INFO
# Provides:          preptmpfs
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Builds tmpfs log dir structure.
# Description:       Ensures there are directories in tmpfs for logging.
### END INIT INFO

echo -n "Populating tmpfs..."

/bin/mkdir -p /var/cache/apt/archives/partial &>/dev/null
/bin/mkdir -p /var/lib/apt/lists/partial &>/dev/null

/bin/mkdir /var/log/apache2 &>/dev/null
/bin/mkdir /var/log/apt &>/dev/null
/bin/mkdir /var/log/fsck &>/dev/null

echo " done."
exit 0
