#!/bin/sh

# preptmpfs v1.04 (21st February 2014)
#  Makes sure there are directories in the tmpfs logging area.

echo -n "Populating tmpfs..."

/bin/mkdir -p /var/cache/apt/archives/partial &>/dev/null
/bin/mkdir -p /var/lib/apt/lists/partial &>/dev/null

/bin/mkdir /var/log/apache2 &>/dev/null
/bin/mkdir /var/log/apt &>/dev/null
/bin/mkdir /var/log/fsck &>/dev/null

echo " done."
