#!/usr/bin/env bash

# of-heartbeat v1.04 (10th April 2020)
#  Automated updates without reimaging.

SERVER="https://openbeak.net"
PULSE="/hb/heartbeat.php"

outputmac() {
	MACW=$(ip link | sed -n '/wlan0/{n;p;}' | awk -F\  {'print $2'})
	MACE=$(ip link | sed -n '/eth0/{n;p;}' | awk -F\  {'print $2'})
	[[ "$MACW" == "" ]] && MACW="00:00:00:00:00:00"
	[[ "$MACE" == "" ]] && MACW="00:00:00:00:00:00"
	echo "$MACW"/"$MACE" > /tmp/openframe.mac
}

# Wait for the system to come to life.
[[ $# -gt 0 ]] && sleep 60

while true; do

	/usr/bin/timeout 1 /bin/ping -c 1 openbeak.net &>/dev/null
	if [[ $? -eq 0 ]] && [ -e /tmp/openframe.uid ]; then
		outputmac

		UPANDLOAD="$(awk -F. {'print $1'} /proc/uptime)"/"$(sed -e 's/\//-/g' -e 's/ /\//g' /proc/loadavg)"
		USER_AGENT="$(cat /tmp/openframe.uid)"/"$(cat /tmp/openframe.mac)"/"$(cat /tmp/openframe.nfo)"/"$(cat /tmp/openframe.ver)"/"$UPANDLOAD"
		OFSCRIPTS_VER=$(cat /usr/local/sbin/of-scripts.ver)
		PULSE_RESPONSE=$(/usr/bin/curl -sA "$USER_AGENT" "$SERVER$PULSE?ver=$OFSCRIPTS_VER" )

		if [[ "$PULSE_RESPONSE" == "OK" ]]; then

			echo "Pulse successful."

		elif [[ "$PULSE_RESPONSE" =~ "https://" ]]; then

			echo "Updating..."

			/usr/bin/timeout 10 /usr/bin/wget -o /dev/null -e robots=off --no-parent -r -A 'of-*' -P /tmp/ "$PULSE_RESPONSE"

			TMP_PATH=$(echo "$PULSE_RESPONSE" | awk -Fhttps:// '{print $2}')
			TMP_HOST=$(echo "$TMP_PATH" | awk -F/ '{print $1}')

			rm -rf /usr/local/sbin/of-*
			cp /tmp/"$TMP_PATH"of-* /usr/local/sbin
			chown root:root /usr/local/sbin/of-*
			chmod 755 /usr/local/sbin/of-*
			chmod 644 /usr/local/sbin/of-*.ver
			rm -rf /tmp/"$TMP_HOST"

			systemctl restart of-heartbeat

		elif [[ "$PULSE_RESPONSE" =~ "http://" ]]; then

			echo "Pulse returned an insecure HTTP address. Not interested."

		else

			echo "Unknown response."

		fi

		# Pulse again tomorrow.
		[[ $# -gt 0 ]] && /bin/sleep 86400 || exit 0
	else
		outputmac
		[[ $# -gt 0 ]] && /bin/sleep 600 || exit 0
	fi

done

exit 0
