#!/usr/bin/env bash

## of-identifier v2.24 (28th April 2020)
##  Identifies what kind of OpenFrame device we're running on and applies some tweaks.

source /etc/lsb-release

OPENFRAME=1
KERNVER=$(uname -r)
KERNMAJVER=$(echo "$KERNVER" | awk -F. '{print $1}')

# We can't do anything useful until the system has decided upon its MAC addresses. This relies upon of-netplan.
while [ ! -f /tmp/openframe.net ]; do sleep 1; done
sync

applystac9202pinpatch() {
	if [ ! -f /etc/modprobe.d/of1-stac9202.conf ]; then
	echo -n "Applying STAC9202 audio patch for kernel series v$KERNMAJVER..."
		if [ $KERNMAJVER -lt 4 ]; then
			echo "options snd-hda-intel position_fix=1 bdl_pos_adj=64 patch=of1-stac9202v$KERNMAJVER.patch" > /etc/modprobe.d/of1-stac9202.conf
		else
			echo "options snd-hda-intel patch=of1-stac9202v$KERNMAJVER.patch" > /etc/modprobe.d/of1-stac9202.conf
		fi
		/sbin/alsa force-reload &>/dev/null
		echo " done."
	fi
}

removestac9202pinpatch() {
	if [ -f /etc/modprobe.d/of1-stac9202.conf ]; then
		echo -n "Removing STAC9202 audio configuration..."
		rm /etc/modprobe.d/of1-stac9202.conf
		/sbin/alsa force-reload &>/dev/null
		echo " done."
	fi
}

outputsysteminformation() {
	DESC=$(echo ${DISTRIB_DESCRIPTION,,} | awk -F' ' '{print $1 "/" $2}')
	MMRY=$(free -b | grep 'Mem:' | tr -s ' ' | cut -c6- | sed 's/ /\//g')
	DRVE=$(df -B 1 | grep '/$' | sed 's/\/dev\///g' | tr -s ' ' | rev | cut -c3- | rev | sed 's/ /\//g')
	ICPU=$(grep -Em1 "^model name.*Intel" /proc/cpuinfo | awk -F\  '{print $7}')
	echo -n "$DESC"/"${DISTRIB_CODENAME,,}"/"$(uname -r)"/"$MMRY"/"$DRVE" > /tmp/openframe.nfo
	echo -n "/$ICPU" >> /tmp/openframe.nfo || echo >> /tmp/openframe.nfo
	echo "/openframe" >> /tmp/openframe.nfo
}

outputsystemuid() {
	UUID=$(cat /etc/fstab | grep 'UUID' | grep ' / ' | awk -F\= '{print $2}' | awk -F\  '{print $1}')
	echo "$UUID" > /tmp/openframe.uid
}

if [ -e /boot/openframe.ver ]; then

	OPENFRAME=`cat /boot/openframe.ver | cut -b1`
	MMCSIZE=""
	echo "Specified as OpenFrame $OPENFRAME via override file."

else

	MMC=`/bin/ls -1 /dev/mmcblk* 2>/dev/null | grep -v "p"`

	if [ "$MMC" != "" ]; then

		MMCCOUNT=`/bin/echo "$MMC" | /usr/bin/wc -l`

		if [ $MMCCOUNT -le 1 ];  then

			# If only one /dev/mmcblk appears, we can use it to identify the unit.

			MMCNUM=`echo "${MMC: -1}"`
			MMCSIZE=`/sbin/fdisk -l /dev/mmcblk$MMCNUM | grep -m1 mmcblk$MMCNUM: | awk -F\  {'print $5'}`

			if [ $MMCSIZE -gt 1028128768 ]; then
				OPENFRAME=2
			fi

			if [ ! $MMCSIZE -gt 0 ]; then
				echo "Could not identify MMC capacity. Assuming OpenFrame 1."
			#else
				#echo "OpenFrame $OPENFRAME with "$(($MMCSIZE/1024/1024))" MB internal storage."
			fi

		else

			# If we get more than one, we can't guarantee which is the internal one.
			echo "Multiple MMC devices found. Assuming OpenFrame 1."

		fi

	else

		echo "Could not identify an MMC device. Assuming OpenFrame 1."

	fi

fi

[ ! $OPENFRAME ] || [ $OPENFRAME -lt 1 ] || [ $OPENFRAME -gt 2 ] && echo "Not a known device." && exit 1

echo $OPENFRAME > /tmp/openframe.ver

if [ "$OPENFRAME" -eq 1 ]; then
	## Here be the OpenFrame 1 tweaks.
	applystac9202pinpatch

elif [ "$OPENFRAME" -eq 2 ]; then
	## Here be the OpenFrame 2 tweaks.
	removestac9202pinpatch

else

	echo "Unable to identify this device. Is it an OpenFrame?"
	exit 1

fi

if [ -f /etc/firstboot ]; then

	# Apply a new UUID to the root partition and rename boot and root to avoid conflicts.
	CODEPRE=${DISTRIB_CODENAME: 0:3}
	BOOTLOC=`/sbin/blkid | grep ${CODEPRE^^}-BOOT | awk -F\: {'print $1'}`
	ROOTLOC=`/sbin/blkid | grep ${CODEPRE^^}-ROOT | awk -F\: {'print $1'}`
	NEWUUID=`/usr/bin/uuid`
	NEWUUIDSHORT="${NEWUUID:0:4}"

	if [[ "$BOOTLOC" != "" ]]; then
		sed -i 's/LABEL=BIO-BOOT/LABEL='BOOT${NEWUUIDSHORT^^}'/g' /etc/fstab
		/sbin/dosfslabel $BOOTLOC "BOOT${NEWUUIDSHORT^^}" >/dev/null 2>&1
	else
		echo "Change of label aborted. Cannot find the boot partition labelled '${CODEPRE^^}-BOOT'."
	fi

	if [[ "$ROOTLOC" != "" ]]; then
		/sbin/tune2fs $ROOTLOC -U $NEWUUID >/dev/null
		sed -i 's/LABEL=BIO-ROOT/UUID='$NEWUUID'/g' /boot/grub.cfg
		sed -i 's/LABEL=BIO-ROOT/UUID='$NEWUUID'/g' /etc/fstab
		/sbin/e2label $ROOTLOC "ROOT${NEWUUIDSHORT^^}"
	else
		echo "Change of UUID aborted. Cannot find the root partition labelled '${CODEPRE^^}-ROOT'."
	fi

	# Set a sensible default audio level.
	/usr/bin/amixer -c 0 sset "Master" 50% unmute >/dev/null 2>&1

	rm /etc/firstboot

fi

outputsystemuid
outputsysteminformation

if [ -f /root/expanding ]; then
	echo "Expanding root filesystem..."
	cp /root/expanding /tmp/expanding
	/sbin/resize2fs `cat /root/expanding`
	rm /root/expanding /tmp/expanding
fi

exit 0
