#!/usr/bin/env bash

# of-settings v1.07 (3rd May 2020)
#  Bundles a bunch of short settings tweaks in one place.

usage() {
	echo "Usage: $0 <option> [options]"
	echo
	echo "  autologin <user>               :  Toggles automatic login on tty1 via getty."
	echo "  autorunx <user> <cmd>          :  Command to run as part of Xserver startup using .xinitrc."
	echo "  autostartx <user>              :  Creates systemd service to start Xserver as <user> at boot."
	echo "  expand                         :  Expands the root partition to fill the drive."
	echo "  grubquiet <enable|disable>     :  Silent GRUB prints nothing to the screen. Default is disabled."
	echo "  rootssh <enable|disable>       :  Allows password-based authentication for root over SSH."
	echo "  splash <name>                  :  Sets the splash screen theme and rebuilds initrd. No theme name disables."
	echo "  sudonopasswd <enable|disable>  :  Permit any user to execute sudo commands with no additional authentication."
	echo
	exit 1
}

if [ $# -lt 1 ] || [[ "$1" == "-h" ]]; then
	usage
fi

if [ "$USER" != "root" ]; then
  echo "You need to run this with superuser privileges. Try 'sudo $0'."
  exit 1
fi

THISSCRIPTPATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"

countdown() {
	MSG="$1"
	SEC=$2
	tput civis
	while [ $SEC -gt 0 ]; do
		echo -ne "$MSG in $SEC\033[0K\r"
		sleep 1
		: $((SEC--))
	done
	echo -e "$MSG now..."
	tput cnorm
}


# Toggles automatic login on tty1 via getty.
if [[ "${1}" == "autologin" ]]; then

	AUTOLOGINUSER="${2}"

	[ ! -d /etc/systemd/system/getty@tty1.service.d ] && mkdir -p /etc/systemd/system/getty@tty1.service.d

	if [ ! -f /etc/systemd/system/getty@tty1.service.d/autologin.conf ]; then

		echo -n "Enabling auto-login for user '$AUTOLOGINUSER'..."
		echo -e "[Service]\nExecStart=\nExecStart=-/sbin/agetty -a $AUTOLOGINUSER --noclear %I \$TERM\n" > /etc/systemd/system/getty@tty1.service.d/autologin.conf

	else

		echo -n "Disabling auto-login..."
		rm /etc/systemd/system/getty@tty1.service.d/autologin.conf

	fi

	echo " done."
	exit 0

fi


# Command to run as part of X.Org Server startup using .xinitrc.
if [[ "${1}" == "autorunx" ]]; then

	if [ "$#" -ne 3 ]; then

		usage

	else

		TARGETUSER="${2}"
		TARGETCMD="${3}"

		if [ -d /home/$TARGETUSER ] && [ ! -f /home/$TARGETUSER/.xinitrc ]; then

			echo -n "Writing /home/$TARGETUSER/.xinitrc..."
			echo -e "export DISPLAY=:0.0\nsetterm -blank 0 -powersave off -powerdown 0\nxset dpms 0 0 0 s off\n[ -x $TARGETCMD ] && $TARGETCMD || /usr/bin/xterm" > /home/$TARGETUSER/.xinitrc
			chown $TARGETUSER:$TARGETUSER /home/$TARGETUSER/.xinitrc
			echo " done."
			exit 0

		elif [ -d /home/$TARGETUSER ] && [ -f /home/$TARGETUSER/.xinitrc ]; then
			
			echo "Found existing /home/$TARGETUSER/.xinitrc. Please remove it and try again."
			exit 1

		else

			echo "No home directory found for user '$TARGETUSER'."
			exit 1

		fi

	fi

fi


# Creates systemd service to start Xserver as <user> at boot.
if [[ "${1}" == "autostartx" ]]; then

	# Need a username!
	[ $# -ne 2 ] && usage

	# Check whether the given user exists.
	getent passwd ${2} &>/dev/null
	USEREXISTS="$?"
	
	if [[ "$USEREXISTS" -ne 0 ]]; then
		echo "Cannot find user '${2}'."
		exit 1
	fi

	# Check whether X.Org Server is installed.
	if [ ! -x /usr/bin/startx ]; then
		echo "Xserver is not installed."
		exit 1
	fi

	# Build the service file.
	AUTOSTARTXSERVICE="[Unit]
Description=Trigger startx before login prompts.
Before=getty@tty1.service getty@tty2.service getty@tty3.service getty@tty4.service getty@tty5.service getty@tty6.service

[Service]
Type=oneshot
User=${2}
ExecStart=/usr/bin/startx -- :0

[Install]
WantedBy=multi-user.target"

	# Install service is user and Xserver exist.
	echo "$AUTOSTARTXSERVICE" > /lib/systemd/system/startx.service
	systemctl enable startx.service

fi


# Expands the root partition to fill the drive.
if [[ "${1}" == "expand" ]]; then

	$THISSCRIPTPATH/of-expand

fi


# Expands the root partition to fill the drive.
if [[ "${1}" == "grubquiet" ]]; then

	if [[ "${2}" == "" ]] || [[ "${2}" == "enable" ]] || [[ "${2}" == "1" ]]; then

		echo -n "Enabling '${1}'..."
		echo -e "fs1:grubq\nfs0:grubq" > /boot/boot.nsh

	else

		echo -n "Disabling '${1}'..."
		echo -e "fs1:grub\nfs0:grub" > /boot/boot.nsh

	fi

	echo " done."
	exit 0

fi


# Allows password-based authentication for root over SSH.
if [[ "${1}" == "rootssh" ]]; then

	PRSMSG="# Allows password-based authentication for root over SSH."
	PRSSET="PermitRootLogin yes"
	PRSCFG="/etc/ssh/sshd_config"

	if [[ "${2}" == "" ]] || [[ "${2}" == "enable" ]] || [[ "${2}" == "1" ]]; then

		echo -n "Enabling '${1}'..."

		if [[ $(grep -c "$PRSSET" "$PRSCFG") -gt 0 ]]; then
			echo " already enabled."
			exit 1
		fi

		echo >> $PRSCFG
		echo $PRSMSG >> $PRSCFG
		echo $PRSSET >> $PRSCFG

	else

		echo -n "Disabling '${1}'..."
		sed -i "/$PRSMSG/d" $PRSCFG
		sed -i "/$PRSSET/d" $PRSCFG
		sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' $PRSCFG

	fi

	systemctl restart sshd.service

	echo " done."
	exit 0

fi


# Sets the splash screen theme and rebuilds initrd.
if [[ "${1}" == "splash" ]]; then

	GRUBCFG=$(cat /boot/grub.cfg | grep vmlinuz)
	PLYMOUTHTHEMESLOC="/usr/share/plymouth/themes"

	if [[ "${2}" != "" ]]; then

		# Check we've been given a valid theme name.
		if [ ! -d "$PLYMOUTHTHEMESLOC"/"${2}" ]; then

			echo "Theme '${2}' not found in $PLYMOUTHTHEMESLOC. Available themes are:"
			echo

			for d in /usr/share/plymouth/themes/*/; do
				echo "$d" | awk -F'/' {'print $(NF-1)'}
			done

			exit 1

		else

			PLYMOUTHCURRENTTHEME=$(update-alternatives --get-selections | grep default.plymouth)

			# Make sure we have the 'splash' option in GRUB config.
			[[ "$GRUBCFG" =~ "splash" ]] || sed -i "s,$GRUBCFG,$GRUBCFG splash,g" /boot/grub.cfg

			if [[ "$PLYMOUTHCURRENTTHEME" =~ "${2}.plymouth" ]]; then

				echo "Theme '${2}' is already selected."
				exit 1

			else

				echo -n "Configuring splash theme '${2}'..."
				update-alternatives --remove-all default.plymouth 2>/dev/null
				update-alternatives --remove-all text.plymouth 2>/dev/null
				update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/"${2}"/"${2}".plymouth 100 &>/dev/null

				echo -n " updating initramfs..."
				update-initramfs -u &>/dev/null

			fi

		fi

	else

		echo -n "Disabling splash screens..."
		[[ "$GRUBCFG" =~ "splash" ]] && sed -i "s, splash,,g" /boot/grub.cfg

	fi

	echo " done."
	exit 0

fi


# Punches a big hole in your security for convenience!
if [[ "${1}" == "sudonopasswd" ]]; then

	SNPMSG="# SECURITY RISK! Allow any user to execute commands with root privileges with no additional authentication."
	SNPSET="%admin ALL=(ALL) NOPASSWD: ALL"
	SNPCFG="/etc/sudoers"

	if [[ "${2}" == "" ]] || [[ "${2}" == "enable" ]] || [[ "${2}" == "1" ]]; then

		echo "This is a terrible idea for security. Please disable at the earliest opportunity."

		echo -n "Enabling '${1}'..."

		if [[ $(grep -c "$SNPSET" "$SNPCFG") -gt 0 ]]; then
			echo " already enabled."
			exit 1
		fi

		echo >> $SNPCFG
		echo $SNPMSG >> $SNPCFG
		echo $SNPSET >> $SNPCFG

	else

		echo -n "Disabling '${1}'..."
		sed -i "/$SNPMSG/d" $SNPCFG
		sed -i "/$SNPSET/d" $SNPCFG
		sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' $SNPCFG

	fi

	echo " done."
	exit 0

fi

exit 0
