#!/usr/bin/env bash

## of-install v1.23 (16th March 2026)
##  Simple installers for software on OpenFrames.

usage() {
	echo "Usage: $0 <option> [options]"
	echo
	echo "  build        :  Installs kernel headers and essential build components."
	echo "  mplayer      :  Installs mplayer with OpenFrame settings."
	echo "  squeezeplay  :  Installs SqueezePlay and the X.Org Server."
	echo "  xserver      :  Installs the X.Org Server."
	echo
	exit 1
}

if [ "$#" -lt 1 ] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
	usage
fi

if [ "$(id -u)" -ne 0 ]; then
	echo "You need to run this with superuser privileges. Try 'sudo $0'."
	exit 1
fi


### Setup

KERNMAJVER=$(uname -r | awk -F. '{print $1}')
KERNMIDVER=$(uname -r | awk -F. '{print $2}')


### Installers


build() {

	### Configuration #####
	KERNELSERVER="https://openbeak.net/openframe/kernel"
	#######################

	KERNELFETCHURL="${KERNELSERVER}/${KERNMAJVER}.${KERNMIDVER}/$(uname -r)/"
	echo "$KERNELFETCHURL"

	echo -n "Downloading $(uname -r) kernel packages..."
	mkdir -p "/tmp/$(uname -r)"
	if wget -q -r -l1 -nd -N -np -A.deb -erobots=off -P "/tmp/$(uname -r)" "$KERNELFETCHURL"; then

		echo " done."
		echo "Installing headers..."
		dpkg -i "/tmp/$(uname -r)/linux-headers"*.deb
		echo "Installing build-essential..."
		apt-get update
		apt-get -y install autoconf build-essential git

	else

		echo "Download failed."
		exit 1

	fi

	sync
	echo "Installation of build environment completed."

}


mplayer() {

	echo "Installing mplayer..."
	echo
	apt-get -y install mplayer

	cat >> /etc/mplayer/mplayer.conf << 'EOF'

###OpenFrame Specific
vo=x11
va=x11
ao=alsa
zoom=yes
fs=yes
EOF

	cat >> /etc/mplayer/input.conf << 'EOF'

###OpenFrame Specific
MOUSE_BTN0_DBL quit
MOUSE_BTN0-MOUSE_BTN0_DBL quit
EOF

	sync
	echo "Installation of mplayer completed."

}


xserver() {

	apt-get -y install xserver-xorg xserver-xorg-legacy x11-utils xinit xterm
	of-settings xdefaults

	sync
	echo "Installation of Xserver completed."

}


### Triggers

echo "Installing ${1}..."
echo

case "${1}" in

	build)
		apt update
		build
	;;

	mplayer)
		[ ! -x /usr/bin/xinit ] && apt update && xserver
		mplayer
	;;

	squeezeplay)
		[ ! -x /usr/bin/xinit ] && apt update && xserver
		squeezeplay
	;;

	xserver)
		apt update
		xserver
	;;

	*)
		echo "No installation script for '${1}'."
		exit 1
	;;

esac

exit 0
