#!/bin/bash

# of-prep.sh v1.61 (29th August 2018)
#  Set up the basics.

#set -x


OPENFRAMEUSER="root"


##  Things to do before installing the kernel.


echo
echo "-- Permissions and Customisation"
echo
sleep 2

echo "Generating en_GB.UTF-8 locale..."
echo
locale-gen en_GB.UTF-8
mv /etc/localtime /etc/localtime.dist
ln -s /usr/share/zoneinfo/Europe/London /etc/localtime
LANG=en_GB.UTF-8
LC_MESSAGES=POSIX
echo

if [ "$OPENFRAMEUSER" != "root" ]; then

	echo "Creating '$OPENFRAMEUSER' user and setting policy..."
	# Create user with 'joggler' as the password.
	useradd -m -p sa0dkJX04f4tM -s /bin/bash $OPENFRAMEUSER
	addgroup admin
	adduser $OPENFRAMEUSER admin
	adduser $OPENFRAMEUSER audio
	adduser $OPENFRAMEUSER tty
	adduser $OPENFRAMEUSER video
	HOMEPATH="/home/$OPENFRAMEUSER"
	echo

else

	echo "root:joggler" | chpasswd
	HOMEPATH="/root"

fi

echo "Setting login preferences..."
sed -i "s/OPENFRAMEUSER/$OPENFRAMEUSER/" /etc/systemd/system/getty@tty1.service.d/override.conf
echo "%admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# echo "Waiting for network..."
# until ping -c 3 1.1.1.1 &>/dev/null
# do
# 	sleep 1
# done
# echo

echo "Running up apt..."
echo
sleep 4

## Update and remove some stuff.
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade

## System Goodies

# nfs-common 		- DO NOT add nfs-common here. It stuffs up rebooting and has to be installed once the system is live.
APT_SYSTEM="acpi alsa-base alsa-utils bash-completion bc curl dosfstools i2c-tools libbsd0 libdaemon0 libedit2 libio-socket-ssl-perl libnet-ssleay-perl libpango1.0-0 libwrap0 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 linux-firmware nano net-tools ntpdate parted patch pciutils psmisc rsync sudo tcpd usbutils usb-modeswitch usb-modeswitch-data unzip usbmount wget wpasupplicant wireless-tools xauth x11-xserver-utils zlibc"
APT_AUDIO="libmad0 libvorbisidec1 libsoxr0"
APT_SSH="ssh openssh-server"

apt-get install -y $APT_SYSTEM $APT_AUDIO $APT_SSH

echo
sleep 2

echo "Setting sensible audio level..."
echo
/usr/bin/amixer -c 0 sset "Master" 50% unmute
echo

# We use this for simple command line control of yaml files, eg. the netplan config file.
echo "Installing yq..."
curl -o /usr/local/bin/yq https://dl.birdslikewires.net/openframe/deps/yq_linux_386
echo

echo "Clarify user permissions..."
chown root:root /home
[[ "$OPENFRAMEUSER" != "root" ]] && chown -R $OPENFRAMEUSER:$OPENFRAMEUSER $HOMEPATH $HOMEPATH/.*
chmod +s /bin/ping /bin/ping6 /bin/su /usr/bin/sudo /usr/sbin/ntpdate
chown root:root /usr/local/bin/*
chown root:root /usr/local/sbin/*
chmod 755 /usr/local/bin/*
chmod 755 /usr/local/sbin/*
echo

echo "Enable custom systemd services..."
chmod +x /usr/local/sbin/of-*

for f in `ls -1 /lib/systemd/system | grep 'of-' | grep '.service'`; do
  SERVICE=`echo $f | awk -F\.service {'print $1'}`
  /bin/systemctl enable $SERVICE
  echo "Enabled $SERVICE"
done
echo

echo "Enable password authentication for root user over SSH..."
[[ "$OPENFRAMEUSER" == "root" ]] && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo

echo "Configure usbmount..."
cp /temp/usbmount/usbmount.conf /etc/usbmount/usbmount.conf
cp /temp/usbmount/mount.d/* /etc/usbmount/mount.d/
cp /temp/usbmount/umount.d/* /etc/usbmount/umount.d/
chown root:root /etc/usbmount/mount.d/* /etc/usbmount/umount.d/*
chmod 755 /etc/usbmount/mount.d/* /etc/usbmount/umount.d/*
echo

## This one is no longer needed - so long as 'quiet' is used in the boot paramters, initramfs now respects it.
#echo "Silence initramfs..."
#sed -i 's/ || echo "Loading, please wait..."//g' /usr/share/initramfs-tools/init
#echo



## Install the kernel.


echo "-- Kernel Installation"
echo
sleep 2

KERNVER=`ls /mnt/ | grep linux-image | awk -F\- '{print $3}' | awk -F\_ '{print $1}'`

echo "Installing kernel $KERNVER..."
dpkg -i /mnt/linux-*.deb
echo

if [ -f /mnt/fh.ko ]; then
	echo "Installing Intel Firmware Hub module..."
	[ -d /lib/modules/$KERNVER/extra ] || mkdir /lib/modules/$KERNVER/extra
	cp /mnt/fh.ko /lib/modules/$KERNVER/extra/
	chmod 644 /lib/modules/$KERNVER/extra/fh.ko
	depmod -a $KERNVER
	echo
fi

echo "Making initrd..."
sed -i 's/MODULES\=most/MODULES\=dep/g' /etc/initramfs-tools/initramfs.conf
sed -i 's/COMPRESS\=gzip/COMPRESS\=xz/g' /etc/initramfs-tools/initramfs.conf
mkinitramfs -o /boot/initrd.img-$KERNVER $KERNVER 2>/dev/null
sleep 2
echo


## Wind down.


echo "-- Wind Down"
echo
sleep 2

apt-get -y autoremove
apt-get clean
echo

echo "Cleaning..."
rm -rf /etc/apparmor*
rm -rf /temp
rm -rf /var/cache/apt/*.bin
rm -rf /var/lib/apt/lists
mkdir -p /var/lib/apt/lists/partial
echo

echo "Remove SSH host keys..."
rm -v /etc/ssh/ssh_host_*
echo

echo "Prep complete."
exit 0
